tag @s add FlyCinnabar
tag @s add FlyViridian
tag @s add FlyPewter
tag @s add FlyVictory
tag @s add FlyIndigo
tag @s add FlyCeladon
tag @s add FlyFuchsia
tag @s add FlyVermilion
tag @s add FlySaffron
tag @s add FlyCerulean
tag @s add FlyLavender
tag @s add FlyOne
tag @s add FlyTwo
tag @s add FlyThree
tag @s add FlyFour
tag @s add FlyFive
tag @s add FlySix
tag @s add FlySeven
